# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-10 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180131_2205'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('zczx', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='website',
            field=models.URLField(default='www.'),
        ),
    ]
